// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANnh4MURM1gahqHytMb6VkOzCYNmXlVaM',
    appId: '1:270096450242:web:1d50f9a790e399fb7c715b',
    messagingSenderId: '270096450242',
    projectId: 'restaurant-80fed',
    authDomain: 'restaurant-80fed.firebaseapp.com',
    storageBucket: 'restaurant-80fed.appspot.com',
    measurementId: 'G-L59RQRN8WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-2v1RF0qC9zwqX5pbi2q79YFEkGdWc1M',
    appId: '1:270096450242:android:d0b945716c7e23207c715b',
    messagingSenderId: '270096450242',
    projectId: 'restaurant-80fed',
    storageBucket: 'restaurant-80fed.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANnh4MURM1gahqHytMb6VkOzCYNmXlVaM',
    appId: '1:270096450242:web:b10b376e97b1231e7c715b',
    messagingSenderId: '270096450242',
    projectId: 'restaurant-80fed',
    authDomain: 'restaurant-80fed.firebaseapp.com',
    storageBucket: 'restaurant-80fed.appspot.com',
    measurementId: 'G-VJ1FP7PXJW',
  );
}
